import type { AppItem } from './types';

export const APPS: AppItem[] = [
  {
    id: 'study-planner',
    title: '스터디 플래너',
    description: '과목, 공부 시간, 노트, 그룹 공부를 한곳에서 관리합니다.',
    emoji: '📚',
    url: '/apps/study-planner/',
    color: '#55efc4',
    category: 'study',
  },
  {
    id: 'focus-room',
    title: '몰입형 가상 면학실',
    description: '카페, 도서관, 교실 같은 360도 공간에서 집중합니다.',
    emoji: '🏫',
    url: '/apps/focus-room/',
    color: '#5dd0a0',
    category: 'study',
  },
  {
    id: 'virtual-study-room',
    title: '가상 독서실',
    description: '친구와 캠, 화면 공유, 음악봇을 켜고 같이 공부합니다.',
    emoji: '🎥',
    url: '/apps/virtual-study-room/',
    color: '#9fe0c4',
    category: 'study',
  },
  {
    id: 'todo',
    title: 'Todo',
    description: '오늘 할 일을 계획하고 완료 여부를 빠르게 체크합니다.',
    emoji: '✅',
    url: '/apps/todo/',
    color: '#0f766e',
    category: 'study',
  },
  {
    id: 'day-schedule',
    title: '하루 시간표',
    description: '하루를 시간 블록으로 나누고 실행 상태를 관리합니다.',
    emoji: '🗓️',
    url: '/apps/day-schedule/',
    color: '#2563eb',
    category: 'study',
  },
  {
    id: 'cornell-notes',
    title: '코넬 노트',
    description: '단서, 필기, 요약을 나눠 배운 내용을 구조적으로 정리합니다.',
    emoji: '📝',
    url: '/apps/cornell-notes/',
    color: '#a29bfe',
    category: 'study',
  },
  {
    id: 'coding-log',
    title: '코테 일지',
    description: '프로그래머스와 백준 풀이 기록, 접근법, 코드를 정리합니다.',
    emoji: '🧩',
    url: '/apps/coding-log/',
    color: '#2ed573',
    category: 'study',
  },
  {
    id: 'code-run-visualizer',
    title: '코드 실행 시각화',
    description: '코드가 단계별로 실행되는 흐름을 눈으로 확인합니다.',
    emoji: '▶️',
    url: '/apps/code-run-visualizer/',
    color: '#23d18b',
    category: 'study',
  },
  {
    id: 'dev-notes',
    title: '개발자 노트',
    description: '프로젝트별 기능 명세, API 명세, 사용자 분석을 정리합니다.',
    emoji: '📋',
    url: '/apps/dev-notes/',
    color: '#2ed573',
    category: 'dev',
  },
  {
    id: 'dev-action-hub',
    title: '개발 액션 허브',
    description: '개발 노트, GitHub Actions, Discord 알림을 한 화면에서 봅니다.',
    emoji: '⚙️',
    url: '/apps/dev-action-hub/',
    color: '#69d2bd',
    category: 'dev',
  },
  {
    id: 'action-notifier',
    title: 'Action 알리미',
    description: 'GitHub Actions 완료 알림을 푸시로 받아봅니다.',
    emoji: '🔔',
    url: '/apps/action-notifier/',
    color: '#74b9ff',
    category: 'dev',
  },
  {
    id: 'site-macro-extension',
    title: '사이트 액션 매크로',
    description: '웹사이트 클릭, 입력, 스크롤 작업을 정해진 시간에 실행합니다.',
    emoji: '🧭',
    url: '/apps/site-macro-extension/',
    color: '#00dd99',
    category: 'web-extension',
  },
  {
    id: 'site-macro-native-bridge',
    title: '매크로 Windows 브리지',
    description: '확장 프로그램이 Windows 앱에 키보드와 마우스 입력을 보낼 수 있게 연결합니다.',
    emoji: '🪟',
    url: '/apps/site-macro-native-bridge/',
    color: '#315f96',
    category: 'web-extension',
  },
  {
    id: 'webbridge',
    title: 'WebBridge',
    description: 'API가 없는 사이트의 데이터를 웹앱으로 연결하는 브라우저 확장 가이드입니다.',
    emoji: '🌉',
    url: '/apps/webbridge/',
    color: '#38aefa',
    category: 'web-extension',
  },
  {
    id: 'focustime-extension',
    title: 'FocusTime',
    description: '사이트와 Windows 앱 사용 시간을 기록하고 집중 흐름을 확인합니다.',
    emoji: '⏱️',
    url: '/apps/focustime-extension/',
    color: '#13c4a3',
    category: 'web-extension',
  },
  {
    id: 'school-meal',
    title: '학교 급식',
    description: '학교 급식과 시간표를 빠르게 확인합니다.',
    emoji: '🍱',
    url: '/apps/school-meal/',
    color: '#ffa502',
    category: 'life',
  },
  {
    id: 'life-tracker',
    title: 'Life Tracker',
    description: '실패, 버린 시간, 작은 성공을 기록하는 자기 이해 트래커입니다.',
    emoji: '🌱',
    url: '/apps/life-tracker/',
    color: '#70a1ff',
    category: 'life',
    disabled: true,
  },
  {
    id: 'mock-invest',
    title: '모의 투자',
    description: '가상 자산으로 주식 매수, 매도, 포트폴리오 관리를 연습합니다.',
    emoji: '📈',
    url: '/apps/mock-invest/',
    color: '#6fd17b',
    category: 'finance-security',
  },
  {
    id: 'voice-phishing',
    title: '보이스피싱 체험',
    description: '가짜 전화와 음성 상황을 체험하며 대처법을 학습합니다.',
    emoji: '🛡️',
    url: '/apps/voice-phishing/',
    color: '#ff5c68',
    category: 'finance-security',
  },
  { id: 'cs1', title: '습관 트래커', description: '매일 반복할 습관을 설정하고 달성률을 추적합니다.', emoji: '🔁', url: '#', color: '#ffa502', category: 'coming-soon', disabled: true },
  { id: 'cs2', title: '독서 기록', description: '읽은 책, 읽는 중인 책, 읽고 싶은 책을 관리합니다.', emoji: '📖', url: '#', color: '#ff6b81', category: 'coming-soon', disabled: true },
  { id: 'cs3', title: '가계부', description: '수입과 지출을 기록하고 월별 통계를 확인합니다.', emoji: '💰', url: '#', color: '#ffd32a', category: 'coming-soon', disabled: true },
  { id: 'cs4', title: '운동 로그', description: '운동 종류, 시간, 횟수를 기록하고 성장 추이를 봅니다.', emoji: '🏃', url: '#', color: '#ff4757', category: 'coming-soon', disabled: true },
  { id: 'cs5', title: '일기장', description: '하루를 짧게 기록하는 개인 일기입니다.', emoji: '📓', url: '#', color: '#eccc68', category: 'coming-soon', disabled: true },
  { id: 'cs6', title: '목표 관리', description: '단기와 장기 목표를 설정하고 달성 여부를 체크합니다.', emoji: '🎯', url: '#', color: '#a29bfe', category: 'coming-soon', disabled: true },
  { id: 'cs7', title: '링크 저장소', description: '자주 보는 링크와 읽을거리를 깔끔하게 저장합니다.', emoji: '🔖', url: '#', color: '#00cec9', category: 'coming-soon', disabled: true },
  { id: 'cs8', title: '레시피 노트', description: '자주 만드는 요리 레시피를 기록합니다.', emoji: '🍳', url: '#', color: '#e17055', category: 'coming-soon', disabled: true },
  { id: 'cs9', title: '회고 일지', description: '주간, 월간 회고를 작성하고 성장 패턴을 파악합니다.', emoji: '🪞', url: '#', color: '#74b9ff', category: 'coming-soon', disabled: true },
  { id: 'cs11', title: '감정 일기', description: '오늘의 감정을 기록하고 변화 흐름을 시각화합니다.', emoji: '💭', url: '#', color: '#fd79a8', category: 'coming-soon', disabled: true },
  { id: 'cs12', title: '여행 기록', description: '다녀온 여행지와 기억을 사진과 함께 기록합니다.', emoji: '🧳', url: '#', color: '#6c5ce7', category: 'coming-soon', disabled: true },
];
