import type { AppItem } from './types';

export const APPS: AppItem[] = [
  {
    id: 'study-planner',
    title: '스터디 플래너',
    description: '과목별 타이머 + 공부 시간 추적 + 달력 히트맵',
    emoji: '📅',
    url: '/apps/study-planner/',
    color: '#55efc4',
  },
  {
    id: 'focus-room',
    title: '몰입형 가상 면학석',
    description: '카페·도서관·교실 같은 360도 공간에서 노트북으로 공부하는 집중 룸',
    emoji: '🪑',
    url: '/apps/focus-room/',
    color: '#5dd0a0',
  },
  {
    id: 'virtual-study-room',
    title: '가상 독서실',
    description: '내 캠만 실제로 켜고 주변은 AI 스터디 인원처럼 움직이는 혼자 공부방',
    emoji: '🎥',
    url: '/apps/virtual-study-room/',
    color: '#9fe0c4',
  },
  {
    id: 'todo',
    title: 'Todo',
    description: '오늘 할 일을 계획하고 완료 여부를 체크하는 데일리 할 일 관리',
    emoji: '✅',
    url: '/apps/todo/',
    color: '#0f766e',
  },
  {
    id: 'day-schedule',
    title: '하루 시간표',
    description: '오늘 하루를 시간 블록으로 계획하고 실행 여부를 체크',
    emoji: '🗓️',
    url: '/apps/day-schedule/',
    color: '#2563eb',
  },
  {
    id: 'dev-notes',
    title: '개발자 노트',
    description: '프로젝트별 기능명세서, API 명세서, 사용자 분석을 한 곳에',
    emoji: '📒',
    url: '/apps/dev-notes/',
    color: '#2ed573',
  },
  {
    id: 'dev-action-hub',
    title: '개발 액션 허브',
    description: '개발자 노트, GitHub Actions, Discord 알림을 한 화면에서 관리',
    emoji: '🧩',
    url: '/apps/dev-action-hub/',
    color: '#69d2bd',
  },
  {
    id: 'life-tracker',
    title: 'Life Tracker',
    description: '실패, 버린 시간, 작은 성취를 기록하는 자기 이해 플랫폼',
    emoji: '📊',
    url: '/apps/life-tracker/',
    color: '#70a1ff',
    disabled: true,
  },
  {
    id: 'cornell-notes',
    title: '코넬 노트',
    description: '키워드, 세부 내용, 요약으로 배운 내용을 구조적으로 정리',
    emoji: '📝',
    url: '/apps/cornell-notes/',
    color: '#a29bfe',
  },
  {
    id: 'coding-log',
    title: '코테 일지',
    description: '프로그래머스 · 백준 풀이 기록, 접근법과 코드를 정리',
    emoji: '💻',
    url: '/apps/coding-log/',
    color: '#2ed573',
  },
  {
    id: 'school-meal',
    title: '학교 알리미',
    description: '학교 급식과 학급 시간표를 한 곳에서 확인',
    emoji: '🏫',
    url: '/apps/school-meal/',
    color: '#ffa502',
  },
  {
    id: 'mock-invest',
    title: '모의 투자',
    description: '가상 자산으로 주식 매수·매도와 포트폴리오 관리를 연습',
    emoji: '📈',
    url: '/apps/mock-invest/',
    color: '#6fd17b',
  },
  {
    id: 'action-notifier',
    title: 'Action 알리미',
    description: 'GitHub Actions 완료 알림을 웹이 꺼져 있어도 받아보기',
    emoji: '⚙️',
    url: '/apps/action-notifier/',
    color: '#74b9ff',
  },
  {
    id: 'code-run-visualizer',
    title: '코드 실행 시각화',
    description: '코드가 컴파일되고 줄 단위로 실행되는 장면을 영상처럼 확인',
    emoji: '▶️',
    url: '/apps/code-run-visualizer/',
    color: '#23d18b',
  },
  {
    id: 'voice-phishing',
    title: '보이스피싱 체험',
    description: '가짜 전화와 악성 앱 설치 상황을 체험하며 피해 흐름과 대처법을 학습',
    emoji: '📞',
    url: '/apps/voice-phishing/',
    color: '#ff5c68',
  },
  {
    id: 'site-macro-extension',
    title: '사이트 액션 매크로',
    description: '원하는 웹사이트에서 클릭·입력·스크롤 작업을 간격 또는 특정 시간에 실행하는 확장 프로그램',
    emoji: '🖱️',
    url: '/apps/site-macro-extension/',
    color: '#00dd99',
  },
  {
    id: 'site-macro-native-bridge',
    title: '매크로 Windows 브리지',
    description: '사이트 액션 매크로가 Windows 앱에 키 입력과 좌표 클릭을 보낼 수 있게 연결',
    emoji: '🪟',
    url: '/apps/site-macro-native-bridge/',
    color: '#315f96',
  },
  {
    id: 'webbridge',
    title: 'WebBridge',
    description: 'API가 없는 웹사이트도 데이터 추출·자동화·웹훅으로 연결하는 브라우저 확장 가이드',
    emoji: '🌉',
    url: '/apps/webbridge/',
    color: '#38aefa',
  },
  {
    id: 'focustime-extension',
    title: 'FocusTime',
    description: '웹사이트와 Windows 앱 사용 시간을 기록하고 집중 흐름을 확인하는 확장 프로그램',
    emoji: '⏱️',
    url: '/apps/focustime-extension/',
    color: '#13c4a3',
  },
  { id: 'cs1', title: '습관 트래커', description: '매일 반복할 습관을 설정하고 달성률을 추적', emoji: '🔁', url: '#', color: '#ffa502', disabled: true },
  { id: 'cs2', title: '독서 기록', description: '읽은 책, 읽는 중, 읽고 싶은 책을 관리', emoji: '📚', url: '#', color: '#ff6b81', disabled: true },
  { id: 'cs3', title: '가계부', description: '수입과 지출을 기록하고 월별 통계 확인', emoji: '💰', url: '#', color: '#ffd32a', disabled: true },
  { id: 'cs4', title: '운동 로그', description: '운동 종류, 시간, 횟수를 기록하고 성장 추적', emoji: '🏋️', url: '#', color: '#ff4757', disabled: true },
  { id: 'cs5', title: '일기장', description: '날마다 하루를 기록하는 개인 일기', emoji: '✍️', url: '#', color: '#eccc68', disabled: true },
  { id: 'cs6', title: '목표 관리', description: '단기·장기 목표를 설정하고 달성 여부를 체크', emoji: '🎯', url: '#', color: '#a29bfe', disabled: true },
  { id: 'cs7', title: '링크 저장소', description: '나중에 볼 링크, 읽을거리를 깔끔하게 저장', emoji: '🔗', url: '#', color: '#00cec9', disabled: true },
  { id: 'cs8', title: '레시피 노트', description: '자주 해먹는 요리 레시피를 기록', emoji: '🍳', url: '#', color: '#e17055', disabled: true },
  { id: 'cs9', title: '회고 일지', description: '주간·월간 회고를 작성하고 성장 패턴 파악', emoji: '🔍', url: '#', color: '#74b9ff', disabled: true },
  { id: 'cs11', title: '감정 일기', description: '오늘의 감정을 기록하고 감정 변화 흐름을 시각화', emoji: '🌈', url: '#', color: '#fd79a8', disabled: true },
  { id: 'cs12', title: '여행 기록', description: '다녀온 여행지와 기억을 사진과 함께 기록', emoji: '✈️', url: '#', color: '#6c5ce7', disabled: true },
];
